apiVersion: v1
kind: Service
metadata:
  name: kubernetes-docker-app-service
  labels:
    app: kubernetes-docker-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    app: kubernetes-docker-app
