apiVersion: v1
kind: Service
metadata:
  name: docker-cloud-app-service
  labels:
    app: docker-cloud-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: docker-cloud-app
